name: CI

on:
  push:
    branches:
      - main  # Adjust to your main branch name
  pull_request:
    branches:
      - main  # Adjust to your main branch name
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          npm install --save-dev rollup 
          npm run build  # Run npm build script

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ GH_TOKEN }}
          publish_dir: ./dist  # Adjust this to the actual directory where your built files are located
          publish_branch: gh-pages  # Specify the branch to deploy to
